### PR TITLE
fix final test's async issue

### PR DESCRIPTION
**Pull request by bhollan**
Fixes https://github.com/learn-co-curriculum/js-tictactoe-rails-api/issues/15

Should be fixed now.  I had the same issue.

### CODE REVIEW

**Comment by bhollan** [comment]
Just found this again.

@aturkewi @AnnJohn

**Comment by aturkewi** [comment]
Hey @mendelB any chance you can take a peek at this?

Thanks for making this PR @bhollan and a quick FYI, re the email from Thursday, please don't tag Ann anymore :)

**Comment by mendelB** [comment]
I haven't experienced the issue myself, but this seems reasonable so taking your word for it @bhollan :)
Would you not use the jasmine [`done()`](https://jasmine.github.io/2.1/introduction.html#section-Asynchronous_Support) for something like this?
Otherwise, if you don't mind just indenting the inner code into that function, I'll merge.

**Comment by bhollan** [comment]
@mendelB Should be good now.

I think this lab would be good to add to a "cleanup" day or something.  I'd be willing to make any changes you direct.

**Pull request merged**
